In [1]:
import jax.numpy as jnp
from diffrax import diffeqsolve, ODETerm, Dopri5


def f(t, y, args):
    return -y


term = ODETerm(f)
solver = Dopri5()
y0 = jnp.array([2., 3.])
solution = diffeqsolve(term, solver, t0=0, t1=1, dt0=0.1, y0=y0)

In [ ]:
solution.t0

In [ ]:
solution.ys.shape

In [1]:
import flax.linen as nn
from model.actor_critic_rnn import NeuralODE
import jax
import jax.numpy as jnp

rng = jax.random.PRNGKey(0)
coords = jnp.ones((1, 4))

model = NeuralODE(
    encoder=nn.Dense(10),
    derivative_net=nn.Dense(10),
    decoder=nn.Dense(4))
params = jax.jit(model.init)(rng, coords)

In [2]:
@jax.jit
def compute_loss(params, coords, true_coords):
    preds = model.apply(params, coords)
    return jnp.abs(preds - true_coords).sum()


grads = jax.grad(compute_loss)(params, coords, jnp.zeros_like(coords))

In [1]:
import jax
import jax.numpy as jnp
import optax

In [2]:
costs = jnp.array([[[2.1536477 , 2.7017763 , 2.0492606 ],
        [0.8976828 , 2.7900887 , 1.3230644 ],
        [0.8135518 , 1.4669538 , 0.44517508]],

       [[2.5109036 , 2.318946  , 2.1817749 ],
        [2.2890368 , 1.0127853 , 2.1383474 ],
        [2.7151723 , 1.6208652 , 2.499429  ]]]
)

In [3]:
@jax.vmap
def fun(costs):
    agent_idx, landmark_idx = optax.assignment.hungarian_algorithm(costs)
    return agent_idx, landmark_idx

In [ ]:
fun(jnp.stack(costs))

In [3]:
cost32 = costs[0].round(6)

In [13]:
cost32

Array([[2.153648, 2.701776, 2.049261],
       [0.897683, 2.790089, 1.323064],
       [0.813552, 1.466954, 0.445175]], dtype=float32)

In [10]:
jnp.arange(9).reshape(3,3)

Array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

In [11]:
optax.assignment.hungarian_algorithm(jnp.arange(9).reshape(3,3))

(Array([0, 1, 2], dtype=int32), Array([0, 1, 2], dtype=int32))

In [18]:
optax.assignment.hungarian_algorithm(cost32)

(Array([-1, -1, -1], dtype=int32), Array([0, 1, 2], dtype=int32))